---
- name: Add FTD CDO inventory
  hosts: localhost
  tasks:
    - name: Add FTD to CDO and cdFMC
      cisco.cdo.cdo_inventory:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: 'us'
        action: 'add'
        onboard_method: 'cli'
        access_control_policy: 'Default Access Control Policy'
        name: 'Austin'
        device_type: 'ftd'
        license:
          - base
          - threat
          - urlfilter
          - malware
          - plus
      register: added_device
