---
- name: Add ASA CDO inventory
  hosts: localhost
  tasks:
    - name: Add ASA to CDO
      cisco.cdo.cdo_inventory:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: 'us'
        action: 'add'
        sdc: 'CDO_cisco_aahackne-SDC-1'
        name: 'Austin'
        ipv4: '172.30.4.101'
        port: 8443
        device_type: 'asa'
        username: 'aaron'
        password: 'abc123'
      register: added_device
