---
- name: Delete ASA from CDO inventory
  hosts: localhost
  tasks:
    - name: Delete ASA from CDO inventory
      cisco.cdo.cdo_inventory:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: 'us'
        delete:
          name: 'ElPaso'
          device_type: 'ftd'
