---
- name: Get ASA device inventory details
  hosts: localhost
  tasks:
    - name: Get device by name
      cisco.cdo.cdo_inventory:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        filter: "Austin"
      register: named_device

    - name: Print Results for all devices, all fields
      ansible.builtin.debug:
        msg:
          "{{ named_device.stdout }}"

    - name: Get cdo inventory
      cisco.cdo.cdo_inventory:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
      register: cdo_inventory

    - name: Print Results for all devices, all fields
      ansible.builtin.debug:
        msg:
          "{{ cdo_inventory.stdout }}"

    - name: Filter Results for desired data using json query
      ansible.builtin.debug:
        msg:
          "{{ cdo_inventory.stdout | community.general.json_query(jmesquery) }}"
      vars:
        jmesquery: >-
          [*].{name: name, serial:serial, chassisSerial:chassisSerial, softwareVersion: softwareVersion, type:type,
          deviceType:deviceType, uid:uid, ipv4:ipv4, port:port, ignoreCertificate:ignoreCertificate}
